// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Os7D3m7niXE5xYr6ZOnSPDBkpQk5WEc',
    appId: '1:1092048577683:web:041dfeb8aa08d299195966',
    messagingSenderId: '1092048577683',
    projectId: 'wally-95c84',
    authDomain: 'wally-95c84.firebaseapp.com',
    storageBucket: 'wally-95c84.firebasestorage.app',
    measurementId: 'G-XK0RBJNDHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_FQMMP0gnbuC9ZDvGlpdZEo2JPR3qa0',
    appId: '1:1092048577683:android:3a02a99b31b56c2c195966',
    messagingSenderId: '1092048577683',
    projectId: 'wally-95c84',
    storageBucket: 'wally-95c84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrQx-XiV9fgAuIbTfj1LcbV2VLxgfZ7Bs',
    appId: '1:1092048577683:ios:4581a6cbb262dd81195966',
    messagingSenderId: '1092048577683',
    projectId: 'wally-95c84',
    storageBucket: 'wally-95c84.firebasestorage.app',
    androidClientId: '1092048577683-48n9im1530c1mcrr6ome0fbbp400k9u2.apps.googleusercontent.com',
    iosClientId: '1092048577683-pelr7abo1f02gd9v6lr7r2gv0lag8vph.apps.googleusercontent.com',
    iosBundleId: 'com.github.hendrilmendes.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrQx-XiV9fgAuIbTfj1LcbV2VLxgfZ7Bs',
    appId: '1:1092048577683:ios:893923392dfcd3eb195966',
    messagingSenderId: '1092048577683',
    projectId: 'wally-95c84',
    storageBucket: 'wally-95c84.firebasestorage.app',
    androidClientId: '1092048577683-48n9im1530c1mcrr6ome0fbbp400k9u2.apps.googleusercontent.com',
    iosClientId: '1092048577683-kj06icml899kn3uc83h9f6g59a3jk76c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Os7D3m7niXE5xYr6ZOnSPDBkpQk5WEc',
    appId: '1:1092048577683:web:558340e532380dae195966',
    messagingSenderId: '1092048577683',
    projectId: 'wally-95c84',
    authDomain: 'wally-95c84.firebaseapp.com',
    storageBucket: 'wally-95c84.firebasestorage.app',
    measurementId: 'G-SJV7HDYD48',
  );

}