// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOLUarCGvoDbD6cMIHldznE8G_W442Ook',
    appId: '1:68248536741:web:feebccc2c195f7b8dfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    authDomain: 'tarefas-app-66907.firebaseapp.com',
    storageBucket: 'tarefas-app-66907.firebasestorage.app',
    measurementId: 'G-Y80KCTRRLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWF-Il2JrCLJwdWL6oSdJVvaOAzupvz8',
    appId: '1:68248536741:android:e4e0f749b9217319dfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    storageBucket: 'tarefas-app-66907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9C2oBMS9YEn9s3do9XVu80JU7pRlLEBs',
    appId: '1:68248536741:ios:ad84f21da18ec652dfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    storageBucket: 'tarefas-app-66907.firebasestorage.app',
    androidClientId: '68248536741-g65qn8i99vlotlg0lgjqpkf09kveplhv.apps.googleusercontent.com',
    iosClientId: '68248536741-tga4isq27n731ehgujr64g0tm84gdsqf.apps.googleusercontent.com',
    iosBundleId: 'com.github.hendrilmendes.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9C2oBMS9YEn9s3do9XVu80JU7pRlLEBs',
    appId: '1:68248536741:ios:ad84f21da18ec652dfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    storageBucket: 'tarefas-app-66907.firebasestorage.app',
    androidClientId: '68248536741-g65qn8i99vlotlg0lgjqpkf09kveplhv.apps.googleusercontent.com',
    iosClientId: '68248536741-tga4isq27n731ehgujr64g0tm84gdsqf.apps.googleusercontent.com',
    iosBundleId: 'com.github.hendrilmendes.projectx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOLUarCGvoDbD6cMIHldznE8G_W442Ook',
    appId: '1:68248536741:web:b6a15165e7d65b1edfaf4c',
    messagingSenderId: '68248536741',
    projectId: 'tarefas-app-66907',
    authDomain: 'tarefas-app-66907.firebaseapp.com',
    storageBucket: 'tarefas-app-66907.firebasestorage.app',
    measurementId: 'G-M5LW9LPTGB',
  );
}
